alias_maps = $alias_database
broken_sasl_auth_clients = yes
[% IF content_filter %]content_filter = [% content_filter %]
recipient_delimiter = +[% END %]
header_checks = regexp:[% vmail_confi_dir %]/header_checks
local_recipient_maps = $alias_maps
myhostname = [% hostname %]
mynetworks = 127.0.0.0/8
relay_domains = $mydestination, hash:[% vmail_confi_dir %]/relay_domains
smtpd_recipient_restrictions = [% smtpd_recipient_restrictions %]
smtpd_sasl_auth_enable = yes
smtpd_sasl_local_domain = $myhostname
smtpd_sasl_security_options = noanonymous
smtpd_sender_login_maps = hash:[% vmail_confi_dir %]/login_maps
transport_maps = hash:[% vmail_confi_dir %]/vtransportmap
virtual_alias_maps = hash:[% vmail_confi_dir %]/valiasmap
virtual_gid_maps = static:[% vmail_gid %]
virtual_mailbox_base = /var/spool/virtual
virtual_mailbox_domains = hash:[% vmail_confi_dir %]/vmaildomains
virtual_mailbox_lock = dotlock
virtual_mailbox_maps = hash:[% vmail_confi_dir %]/vmailbox
virtual_minimum_uid = [% vmail_uid %]
virtual_uid_maps = static:[% vmail_uid %]
