#!/bin/bash
#
#                  RavenCore Hosting Control Panel
#                Copyright (C) 2005  Corey Henderson
#
#     This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

. /etc/ravencore.conf || exit 1

echo "Enter the hostname of a server with ravencore-database installed: "
read host

echo "Enter the port of a server with ravencore-database installed: "
read port

echo "Enter the database for ravencore on $host: "
read database

echo "Enter the username of the $database database on $host: "
read user

echo "Enter the password for $user at $host: "
read pass

mysql -h $host -u $user -p$pass -e "use $database" &> /dev/null

if [ $? -eq 0 ]; then
	
	cat << EOF > $RC_ROOT/database.cfg
MYSQL_ADMIN_HOST="$host"
MYSQL_ADMIN_PORT="$port"
MYSQL_ADMIN_USER="$user"
MYSQL_ADMIN_DB="$database"
EOF

	echo $pass > $RC_ROOT/.shadow

else

	echo "Unable to make a database connection with given info. Please try again"

fi
