#!/usr/bin/perl
#
#                  RavenCore Hosting Control Panel
#                Copyright (C) 2005  Corey Henderson
#
#     This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

# this script was made to replace the call to the mysql shell command,
# clean up the shell scripts code, and have all SQL queries be pointed at the
# socket, which enables logging of 100% of all sql queries, system wide

use rcsock;

$RC_ROOT = shift(@INC) . '/../..';

$db = new rcsock($RC_ROOT. '/var/rc.sock');

# build our $sql query off of everything given on the command line

foreach (@ARGV)
{
    $sql .= $_ . ' ';
}

# tell our $db object we're running from the shell... skip the "connect" statement

$ENV{DATA_QUERY_SHELL} = 1;

# run the SQL query

@result = $db->data_query($sql);

# return the resutls if there are any

while ( $row = $db->data_fetch_row(\@result) )
{

# we should only really ever have one value in the hash, because the data
# is returned in random order, and all the calls to this script are made
# with one result per row expected anyway, because the ones that need more
# data in one query use the concat() statement and parse the results
    
    foreach (values(%$row))
    {
	print $_ . "\t";
    }
    
    print "\n";
    
}
