#!/bin/bash
#
#                  RavenCore Hosting Control Panel
#                Copyright (C) 2005  Corey Henderson
#
#     This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

. /etc/ravencore.conf || exit 1

# One input paramater, the domain name in which to process logs for

log_file=$1
domain_name=$2

# change directory in the the domain's logs directory

$_cd $VHOST_ROOT/$domain_name/var/log

# check to see if access_log.1 exists

if [ -f $log_file.1 ]; then

# check to see if we have a .local for awstats

    if [ -d $RC_ROOT/var/apps/awstats.local ]; then
	_local=".local"
    else
	_local=""
    fi

# update AWStats on the access_log.1

    case $log_file in
	"access_log") $RC_ROOT/var/apps/awstats$_local/tools/awstats_updateall.pl now -awstatsprog=$RC_ROOT/var/apps/awstats$_local/wwwroot/cgi-bin/awstats.pl -configdir=$VHOST_ROOT/$domain_name/conf/ &> /dev/null;;
    esac

# the processed log probably already exists, so append log.1 to it. If it doesn't
# exist, it will simply be created

    $_cat $log_file.1 >> $log_file.processed

# remove the log we just appended from
    
    $_rm -f $log_file.1

# make sure the log exists

    $_touch $log_file

fi

# check to see if we have custom log rotation setup for this domain by checking both
# the database and if they have a logrotate.conf file

if [ $($DATA_QUERY "select count(name) from domains where logrotate = 'on' and name = '$domain_name'") -eq 1 ] && [ -f ../conf/logrotate.conf ]; then

    $_logrotate ../conf/logrotate.conf

fi
