#!/bin/bash

. /etc/ravencore.conf || exit 1

# One input paramater, the domain name in which to process logs for

log_file=$1
domain_name=$2

# change directory in the the domain's logs directory

cd $VHOST_ROOT/$domain_name/var/log

# check to see if access_log.1 exists

if [ -f $log_file.1 ]; then

# update AWStats on the access_log.1

    case $log_file in
	"access_log") $RC_ROOT/var/awstats/tools/awstats_updateall.pl now -awstatsprog=$RC_ROOT/var/awstats/wwwroot/cgi-bin/awstats.pl -configdir=$VHOST_ROOT/$domain_name/conf/ &> /dev/null;;
    esac

# the processed log probably already exists, so append log.1 to it. If it doesn't
# exist, it will simply be created

    cat $log_file.1 >> $log_file.processed

# remove the log we just appended from
    
    rm -f $log_file.1

# make sure the log exists

    touch $log_file

fi

# check to see if we have custom log rotation setup for this domain by checking both
# the database and if they have a logrotate.conf file

if [ $($MYSQL_STR -e "select count(name) from domains where logrotate = 'on' and name = '$domain_name'" | sed '1d') -eq 1 ] && [ -f ../conf/logrotate.conf ]; then

    /usr/sbin/logrotate ../conf/logrotate.conf

fi
