#!/usr/bin/perl
#
#                  RavenCore Hosting Control Panel
#                Copyright (C) 2005  Corey Henderson
#
#     This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#

#
# This script needs to be ran with the perl -I switch of the RC_ROOT/lib
#

use RavenCore::Server;
use File::Basename;

# name our process
$0 = basename($0);

my $user = 'root';

my $rc = new RavenCore::Server;

$rc->checkconf("term");

# start the back-end daemon
$rc->run(
	 proto => 'unix',
	 port => $rc->{RC_ROOT} . '/var/rc.sock',
	 pid_file => $rc->{RC_ROOT} . '/var/run/rcserver.pid',
	 user => $user,
	 group => $user,
	 log_file => 'Sys::Syslog',
	 syslog_ident => $0,
	 syslog_logopt => 'pid',
	 setsid => 1,
	 background => 1,
	 );

